name: Build Haxo Blog

on:
  push:
    branches: [ "raw" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: node -v
    - run: git branch
    - run: |
        npm install
        hexo clean
        hexo generate
        hexo new page "categories"
        hexo new page "tags"
        hexo new page "about"
        ls -al blog/
    # - run: npm run build --if-present
    # - run: npm test