name: Node.js CI

on:
  push:
    branches: [ "raw" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: node version
    - run: git branch
    # - run: npm run build --if-present
    # - run: npm test